name: Sync next

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  sync:
    uses: Start9Labs/start-technologies/.github/workflows/syncNext.yml@master
    permissions:
      contents: write
      pull-requests: write
